
module.exports = {
    // Activity: require('./activity/Activity.schema'),
    // ActivityCalendar: require('./activity/ActivityCalendar.schema'),
    // ActivityKind: require('./activity/ActivityKind.schema'),
    // ActivityScene: require('./activity/ActivityScene.schema'),
    // ActivityTag: require('./activity/ActivityTag.schema'),
    // Place: require('./place/Place.schema'),
    // City: require('./place/City.schema'),
    // State: require('./place/State.schema'),
    // Profile: require('./profile/Profile.schema'),
    // Education: require('./profile/Education.schema'),
    // Hobby: require('./profile/Hobby.schema'),
    // Interest: require('./profile/Interest.schema'),
    // User: require('./profile/User.schema'),
    // Work: require('./work/Work.schema'),
    // WorkDetail: require('./work/WorkDetail.schema'),
    // Photo: require('./Photo.schema'),
    // Verify: require('./Verify.schema'),
};